services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 endpoint
      - "9001:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init_weights.sh:/init_weights.sh:ro
      - ./latest.pt:/latest.pt:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        mc alias set myminio http://minio:9000 admin admin12345
        mc mb -p myminio/mybucket || true
        /init_weights.sh

  avgsher:
    container_name: avgsher
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      createbuckets:
        condition: service_completed_successfully
    environment:
      PYTHON_BIN_PATH: "python"
      GRPC_PORT: "8081"
      MINIO_ENDPOINT: "minio:9000"
      PATH_TO_PYTHON_SCRIPT: ""
    ports:
      - "8081:8081"
    restart: unless-stopped


volumes:
  minio_data: