// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_usecases.go -package=mocks UpsertWeightsUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "avg_weights_fed_ml_itmo/internal/app/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpsertWeightsUsecase is a mock of UpsertWeightsUsecase interface.
type MockUpsertWeightsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUpsertWeightsUsecaseMockRecorder
	isgomock struct{}
}

// MockUpsertWeightsUsecaseMockRecorder is the mock recorder for MockUpsertWeightsUsecase.
type MockUpsertWeightsUsecaseMockRecorder struct {
	mock *MockUpsertWeightsUsecase
}

// NewMockUpsertWeightsUsecase creates a new mock instance.
func NewMockUpsertWeightsUsecase(ctrl *gomock.Controller) *MockUpsertWeightsUsecase {
	mock := &MockUpsertWeightsUsecase{ctrl: ctrl}
	mock.recorder = &MockUpsertWeightsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpsertWeightsUsecase) EXPECT() *MockUpsertWeightsUsecaseMockRecorder {
	return m.recorder
}

// UpsertWeights mocks base method.
func (m *MockUpsertWeightsUsecase) UpsertWeights(ctx context.Context, domainRequest model.AddMyWeightsDomainReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWeights", ctx, domainRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWeights indicates an expected call of UpsertWeights.
func (mr *MockUpsertWeightsUsecaseMockRecorder) UpsertWeights(ctx, domainRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWeights", reflect.TypeOf((*MockUpsertWeightsUsecase)(nil).UpsertWeights), ctx, domainRequest)
}

// MockGetterWeightsUsecase is a mock of GetterWeightsUsecase interface.
type MockGetterWeightsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetterWeightsUsecaseMockRecorder
	isgomock struct{}
}

// MockGetterWeightsUsecaseMockRecorder is the mock recorder for MockGetterWeightsUsecase.
type MockGetterWeightsUsecaseMockRecorder struct {
	mock *MockGetterWeightsUsecase
}

// NewMockGetterWeightsUsecase creates a new mock instance.
func NewMockGetterWeightsUsecase(ctrl *gomock.Controller) *MockGetterWeightsUsecase {
	mock := &MockGetterWeightsUsecase{ctrl: ctrl}
	mock.recorder = &MockGetterWeightsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetterWeightsUsecase) EXPECT() *MockGetterWeightsUsecaseMockRecorder {
	return m.recorder
}

// GetNewWeights mocks base method.
func (m *MockGetterWeightsUsecase) GetNewWeights(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewWeights", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewWeights indicates an expected call of GetNewWeights.
func (mr *MockGetterWeightsUsecaseMockRecorder) GetNewWeights(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewWeights", reflect.TypeOf((*MockGetterWeightsUsecase)(nil).GetNewWeights), ctx)
}
