// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_upser_weights_usecase.go -package=mocks UpsertWeightsUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "avg_weights_fed_ml_itmo/internal/app/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpsertWeightsUsecase is a mock of UpsertWeightsUsecase interface.
type MockUpsertWeightsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUpsertWeightsUsecaseMockRecorder
	isgomock struct{}
}

// MockUpsertWeightsUsecaseMockRecorder is the mock recorder for MockUpsertWeightsUsecase.
type MockUpsertWeightsUsecaseMockRecorder struct {
	mock *MockUpsertWeightsUsecase
}

// NewMockUpsertWeightsUsecase creates a new mock instance.
func NewMockUpsertWeightsUsecase(ctrl *gomock.Controller) *MockUpsertWeightsUsecase {
	mock := &MockUpsertWeightsUsecase{ctrl: ctrl}
	mock.recorder = &MockUpsertWeightsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpsertWeightsUsecase) EXPECT() *MockUpsertWeightsUsecaseMockRecorder {
	return m.recorder
}

// UpsertWeights mocks base method.
func (m *MockUpsertWeightsUsecase) UpsertWeights(ctx context.Context, domainRequest model.AddMyWeightsDomainReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWeights", ctx, domainRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWeights indicates an expected call of UpsertWeights.
func (mr *MockUpsertWeightsUsecaseMockRecorder) UpsertWeights(ctx, domainRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWeights", reflect.TypeOf((*MockUpsertWeightsUsecase)(nil).UpsertWeights), ctx, domainRequest)
}
