# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serverside.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serverside.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10serverside.proto\x12\nserverside\"O\n\x13\x41\x64\x64MyWeightsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x14\n\x0cnum_examples\x18\x03 \x01(\x04\"\x16\n\x14\x41\x64\x64MyWeightsResponse\"\x1a\n\x18GetReleaseWeightsRequest\"2\n\x19GetReleaseWeightsResponse\x12\x15\n\rlink_to_minio\x18\x01 \x01(\t2\xc5\x01\n\nAvgWeights\x12S\n\x0c\x41\x64\x64MyWeights\x12\x1f.serverside.AddMyWeightsRequest\x1a .serverside.AddMyWeightsResponse\"\x00\x12\x62\n\x11GetReleaseWeights\x12$.serverside.GetReleaseWeightsRequest\x1a%.serverside.GetReleaseWeightsResponse\"\x00\x42\x0eZ\x0c./serversideb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverside_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./serverside'
  _globals['_ADDMYWEIGHTSREQUEST']._serialized_start=32
  _globals['_ADDMYWEIGHTSREQUEST']._serialized_end=111
  _globals['_ADDMYWEIGHTSRESPONSE']._serialized_start=113
  _globals['_ADDMYWEIGHTSRESPONSE']._serialized_end=135
  _globals['_GETRELEASEWEIGHTSREQUEST']._serialized_start=137
  _globals['_GETRELEASEWEIGHTSREQUEST']._serialized_end=163
  _globals['_GETRELEASEWEIGHTSRESPONSE']._serialized_start=165
  _globals['_GETRELEASEWEIGHTSRESPONSE']._serialized_end=215
  _globals['_AVGWEIGHTS']._serialized_start=218
  _globals['_AVGWEIGHTS']._serialized_end=415
# @@protoc_insertion_point(module_scope)
