// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/serverside.proto

package serverside

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMyWeightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Layers        map[string][]byte      `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMyWeightsRequest) Reset() {
	*x = AddMyWeightsRequest{}
	mi := &file_api_serverside_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMyWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMyWeightsRequest) ProtoMessage() {}

func (x *AddMyWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverside_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMyWeightsRequest.ProtoReflect.Descriptor instead.
func (*AddMyWeightsRequest) Descriptor() ([]byte, []int) {
	return file_api_serverside_proto_rawDescGZIP(), []int{0}
}

func (x *AddMyWeightsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddMyWeightsRequest) GetLayers() map[string][]byte {
	if x != nil {
		return x.Layers
	}
	return nil
}

type AddMyWeightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMyWeightsResponse) Reset() {
	*x = AddMyWeightsResponse{}
	mi := &file_api_serverside_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMyWeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMyWeightsResponse) ProtoMessage() {}

func (x *AddMyWeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverside_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMyWeightsResponse.ProtoReflect.Descriptor instead.
func (*AddMyWeightsResponse) Descriptor() ([]byte, []int) {
	return file_api_serverside_proto_rawDescGZIP(), []int{1}
}

var File_api_serverside_proto protoreflect.FileDescriptor

const file_api_serverside_proto_rawDesc = "" +
	"\n" +
	"\x14api/serverside.proto\x12\n" +
	"serverside\"\xb2\x01\n" +
	"\x13AddMyWeightsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12C\n" +
	"\x06layers\x18\x02 \x03(\v2+.serverside.AddMyWeightsRequest.LayersEntryR\x06layers\x1a9\n" +
	"\vLayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x16\n" +
	"\x14AddMyWeightsResponse2a\n" +
	"\n" +
	"AvgWeights\x12S\n" +
	"\fAddMyWeights\x12\x1f.serverside.AddMyWeightsRequest\x1a .serverside.AddMyWeightsResponse\"\x00B\x0eZ\f./serversideb\x06proto3"

var (
	file_api_serverside_proto_rawDescOnce sync.Once
	file_api_serverside_proto_rawDescData []byte
)

func file_api_serverside_proto_rawDescGZIP() []byte {
	file_api_serverside_proto_rawDescOnce.Do(func() {
		file_api_serverside_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_serverside_proto_rawDesc), len(file_api_serverside_proto_rawDesc)))
	})
	return file_api_serverside_proto_rawDescData
}

var file_api_serverside_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_serverside_proto_goTypes = []any{
	(*AddMyWeightsRequest)(nil),  // 0: serverside.AddMyWeightsRequest
	(*AddMyWeightsResponse)(nil), // 1: serverside.AddMyWeightsResponse
	nil,                          // 2: serverside.AddMyWeightsRequest.LayersEntry
}
var file_api_serverside_proto_depIdxs = []int32{
	2, // 0: serverside.AddMyWeightsRequest.layers:type_name -> serverside.AddMyWeightsRequest.LayersEntry
	0, // 1: serverside.AvgWeights.AddMyWeights:input_type -> serverside.AddMyWeightsRequest
	1, // 2: serverside.AvgWeights.AddMyWeights:output_type -> serverside.AddMyWeightsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_serverside_proto_init() }
func file_api_serverside_proto_init() {
	if File_api_serverside_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_serverside_proto_rawDesc), len(file_api_serverside_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_serverside_proto_goTypes,
		DependencyIndexes: file_api_serverside_proto_depIdxs,
		MessageInfos:      file_api_serverside_proto_msgTypes,
	}.Build()
	File_api_serverside_proto = out.File
	file_api_serverside_proto_goTypes = nil
	file_api_serverside_proto_depIdxs = nil
}
