// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/serverside.proto

package serverside

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMyWeightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Айдишник пользака
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// torch.save output
	Weights []byte `protobuf:"bytes,2,opt,name=weights,proto3" json:"weights,omitempty"`
	// для weighted FedAvg (сколько примеров было у этого конкретного пользака)
	NumExamples   uint64 `protobuf:"varint,3,opt,name=num_examples,json=numExamples,proto3" json:"num_examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMyWeightsRequest) Reset() {
	*x = AddMyWeightsRequest{}
	mi := &file_api_serverside_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMyWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMyWeightsRequest) ProtoMessage() {}

func (x *AddMyWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverside_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMyWeightsRequest.ProtoReflect.Descriptor instead.
func (*AddMyWeightsRequest) Descriptor() ([]byte, []int) {
	return file_api_serverside_proto_rawDescGZIP(), []int{0}
}

func (x *AddMyWeightsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddMyWeightsRequest) GetWeights() []byte {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *AddMyWeightsRequest) GetNumExamples() uint64 {
	if x != nil {
		return x.NumExamples
	}
	return 0
}

type AddMyWeightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMyWeightsResponse) Reset() {
	*x = AddMyWeightsResponse{}
	mi := &file_api_serverside_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMyWeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMyWeightsResponse) ProtoMessage() {}

func (x *AddMyWeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverside_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMyWeightsResponse.ProtoReflect.Descriptor instead.
func (*AddMyWeightsResponse) Descriptor() ([]byte, []int) {
	return file_api_serverside_proto_rawDescGZIP(), []int{1}
}

type GetReleaseWeightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleaseWeightsRequest) Reset() {
	*x = GetReleaseWeightsRequest{}
	mi := &file_api_serverside_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleaseWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleaseWeightsRequest) ProtoMessage() {}

func (x *GetReleaseWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverside_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleaseWeightsRequest.ProtoReflect.Descriptor instead.
func (*GetReleaseWeightsRequest) Descriptor() ([]byte, []int) {
	return file_api_serverside_proto_rawDescGZIP(), []int{2}
}

// я пока хз как лучше, прям веса отдавать или просто ссылку на минио.
type GetReleaseWeightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       []byte                 `protobuf:"bytes,1,opt,name=weights,proto3" json:"weights,omitempty"`
	LinkToMinio   string                 `protobuf:"bytes,2,opt,name=link_to_minio,json=linkToMinio,proto3" json:"link_to_minio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleaseWeightsResponse) Reset() {
	*x = GetReleaseWeightsResponse{}
	mi := &file_api_serverside_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleaseWeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleaseWeightsResponse) ProtoMessage() {}

func (x *GetReleaseWeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverside_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleaseWeightsResponse.ProtoReflect.Descriptor instead.
func (*GetReleaseWeightsResponse) Descriptor() ([]byte, []int) {
	return file_api_serverside_proto_rawDescGZIP(), []int{3}
}

func (x *GetReleaseWeightsResponse) GetWeights() []byte {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *GetReleaseWeightsResponse) GetLinkToMinio() string {
	if x != nil {
		return x.LinkToMinio
	}
	return ""
}

var File_api_serverside_proto protoreflect.FileDescriptor

const file_api_serverside_proto_rawDesc = "" +
	"\n" +
	"\x14api/serverside.proto\x12\n" +
	"serverside\"o\n" +
	"\x13AddMyWeightsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\aweights\x18\x02 \x01(\fR\aweights\x12!\n" +
	"\fnum_examples\x18\x03 \x01(\x04R\vnumExamples\"\x16\n" +
	"\x14AddMyWeightsResponse\"\x1a\n" +
	"\x18GetReleaseWeightsRequest\"Y\n" +
	"\x19GetReleaseWeightsResponse\x12\x18\n" +
	"\aweights\x18\x01 \x01(\fR\aweights\x12\"\n" +
	"\rlink_to_minio\x18\x02 \x01(\tR\vlinkToMinio2\xc5\x01\n" +
	"\n" +
	"AvgWeights\x12S\n" +
	"\fAddMyWeights\x12\x1f.serverside.AddMyWeightsRequest\x1a .serverside.AddMyWeightsResponse\"\x00\x12b\n" +
	"\x11GetReleaseWeights\x12$.serverside.GetReleaseWeightsRequest\x1a%.serverside.GetReleaseWeightsResponse\"\x00B\x0eZ\f./serversideb\x06proto3"

var (
	file_api_serverside_proto_rawDescOnce sync.Once
	file_api_serverside_proto_rawDescData []byte
)

func file_api_serverside_proto_rawDescGZIP() []byte {
	file_api_serverside_proto_rawDescOnce.Do(func() {
		file_api_serverside_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_serverside_proto_rawDesc), len(file_api_serverside_proto_rawDesc)))
	})
	return file_api_serverside_proto_rawDescData
}

var file_api_serverside_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_serverside_proto_goTypes = []any{
	(*AddMyWeightsRequest)(nil),       // 0: serverside.AddMyWeightsRequest
	(*AddMyWeightsResponse)(nil),      // 1: serverside.AddMyWeightsResponse
	(*GetReleaseWeightsRequest)(nil),  // 2: serverside.GetReleaseWeightsRequest
	(*GetReleaseWeightsResponse)(nil), // 3: serverside.GetReleaseWeightsResponse
}
var file_api_serverside_proto_depIdxs = []int32{
	0, // 0: serverside.AvgWeights.AddMyWeights:input_type -> serverside.AddMyWeightsRequest
	2, // 1: serverside.AvgWeights.GetReleaseWeights:input_type -> serverside.GetReleaseWeightsRequest
	1, // 2: serverside.AvgWeights.AddMyWeights:output_type -> serverside.AddMyWeightsResponse
	3, // 3: serverside.AvgWeights.GetReleaseWeights:output_type -> serverside.GetReleaseWeightsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_serverside_proto_init() }
func file_api_serverside_proto_init() {
	if File_api_serverside_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_serverside_proto_rawDesc), len(file_api_serverside_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_serverside_proto_goTypes,
		DependencyIndexes: file_api_serverside_proto_depIdxs,
		MessageInfos:      file_api_serverside_proto_msgTypes,
	}.Build()
	File_api_serverside_proto = out.File
	file_api_serverside_proto_goTypes = nil
	file_api_serverside_proto_depIdxs = nil
}
