// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/serverside.proto

package serverside

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AvgWeights_AddMyWeights_FullMethodName      = "/serverside.AvgWeights/AddMyWeights"
	AvgWeights_GetReleaseWeights_FullMethodName = "/serverside.AvgWeights/GetReleaseWeights"
)

// AvgWeightsClient is the client API for AvgWeights service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvgWeightsClient interface {
	AddMyWeights(ctx context.Context, in *AddMyWeightsRequest, opts ...grpc.CallOption) (*AddMyWeightsResponse, error)
	GetReleaseWeights(ctx context.Context, in *GetReleaseWeightsRequest, opts ...grpc.CallOption) (*GetReleaseWeightsResponse, error)
}

type avgWeightsClient struct {
	cc grpc.ClientConnInterface
}

func NewAvgWeightsClient(cc grpc.ClientConnInterface) AvgWeightsClient {
	return &avgWeightsClient{cc}
}

func (c *avgWeightsClient) AddMyWeights(ctx context.Context, in *AddMyWeightsRequest, opts ...grpc.CallOption) (*AddMyWeightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMyWeightsResponse)
	err := c.cc.Invoke(ctx, AvgWeights_AddMyWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avgWeightsClient) GetReleaseWeights(ctx context.Context, in *GetReleaseWeightsRequest, opts ...grpc.CallOption) (*GetReleaseWeightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReleaseWeightsResponse)
	err := c.cc.Invoke(ctx, AvgWeights_GetReleaseWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvgWeightsServer is the server API for AvgWeights service.
// All implementations must embed UnimplementedAvgWeightsServer
// for forward compatibility.
type AvgWeightsServer interface {
	AddMyWeights(context.Context, *AddMyWeightsRequest) (*AddMyWeightsResponse, error)
	GetReleaseWeights(context.Context, *GetReleaseWeightsRequest) (*GetReleaseWeightsResponse, error)
	mustEmbedUnimplementedAvgWeightsServer()
}

// UnimplementedAvgWeightsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvgWeightsServer struct{}

func (UnimplementedAvgWeightsServer) AddMyWeights(context.Context, *AddMyWeightsRequest) (*AddMyWeightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMyWeights not implemented")
}
func (UnimplementedAvgWeightsServer) GetReleaseWeights(context.Context, *GetReleaseWeightsRequest) (*GetReleaseWeightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReleaseWeights not implemented")
}
func (UnimplementedAvgWeightsServer) mustEmbedUnimplementedAvgWeightsServer() {}
func (UnimplementedAvgWeightsServer) testEmbeddedByValue()                    {}

// UnsafeAvgWeightsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvgWeightsServer will
// result in compilation errors.
type UnsafeAvgWeightsServer interface {
	mustEmbedUnimplementedAvgWeightsServer()
}

func RegisterAvgWeightsServer(s grpc.ServiceRegistrar, srv AvgWeightsServer) {
	// If the following call panics, it indicates UnimplementedAvgWeightsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AvgWeights_ServiceDesc, srv)
}

func _AvgWeights_AddMyWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMyWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvgWeightsServer).AddMyWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvgWeights_AddMyWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvgWeightsServer).AddMyWeights(ctx, req.(*AddMyWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvgWeights_GetReleaseWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvgWeightsServer).GetReleaseWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvgWeights_GetReleaseWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvgWeightsServer).GetReleaseWeights(ctx, req.(*GetReleaseWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvgWeights_ServiceDesc is the grpc.ServiceDesc for AvgWeights service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvgWeights_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serverside.AvgWeights",
	HandlerType: (*AvgWeightsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMyWeights",
			Handler:    _AvgWeights_AddMyWeights_Handler,
		},
		{
			MethodName: "GetReleaseWeights",
			Handler:    _AvgWeights_GetReleaseWeights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/serverside.proto",
}
