// Code generated by MockGen. DO NOT EDIT.
// Source: add_my_weights_usecase.go
//
// Generated by this command:
//
//	mockgen -source=add_my_weights_usecase.go -destination=mocks/mock_weights_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWeightsRepo is a mock of WeightsRepo interface.
type MockWeightsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWeightsRepoMockRecorder
	isgomock struct{}
}

// MockWeightsRepoMockRecorder is the mock recorder for MockWeightsRepo.
type MockWeightsRepoMockRecorder struct {
	mock *MockWeightsRepo
}

// NewMockWeightsRepo creates a new mock instance.
func NewMockWeightsRepo(ctrl *gomock.Controller) *MockWeightsRepo {
	mock := &MockWeightsRepo{ctrl: ctrl}
	mock.recorder = &MockWeightsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeightsRepo) EXPECT() *MockWeightsRepoMockRecorder {
	return m.recorder
}

// PutNewWeights mocks base method.
func (m *MockWeightsRepo) PutNewWeights(ctx context.Context, objectKey string, weights []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNewWeights", ctx, objectKey, weights)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutNewWeights indicates an expected call of PutNewWeights.
func (mr *MockWeightsRepoMockRecorder) PutNewWeights(ctx, objectKey, weights any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNewWeights", reflect.TypeOf((*MockWeightsRepo)(nil).PutNewWeights), ctx, objectKey, weights)
}
