// Code generated by MockGen. DO NOT EDIT.
// Source: get_release_weigths.go
//
// Generated by this command:
//
//	mockgen -source=get_release_weigths.go -destination=mocks/mock_get_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetWeightsRepo is a mock of GetWeightsRepo interface.
type MockGetWeightsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGetWeightsRepoMockRecorder
	isgomock struct{}
}

// MockGetWeightsRepoMockRecorder is the mock recorder for MockGetWeightsRepo.
type MockGetWeightsRepoMockRecorder struct {
	mock *MockGetWeightsRepo
}

// NewMockGetWeightsRepo creates a new mock instance.
func NewMockGetWeightsRepo(ctrl *gomock.Controller) *MockGetWeightsRepo {
	mock := &MockGetWeightsRepo{ctrl: ctrl}
	mock.recorder = &MockGetWeightsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetWeightsRepo) EXPECT() *MockGetWeightsRepoMockRecorder {
	return m.recorder
}

// GetDownloadURL mocks base method.
func (m *MockGetWeightsRepo) GetDownloadURL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadURL indicates an expected call of GetDownloadURL.
func (mr *MockGetWeightsRepoMockRecorder) GetDownloadURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadURL", reflect.TypeOf((*MockGetWeightsRepo)(nil).GetDownloadURL), ctx)
}
