from golang:1.24 as builder

workdir /app

copy go.mod go.sum ./
run go mod download

copy . .

run CGO_ENABLED=0 GOOS=linux go build -o avg-weights-server ./cmd/server/main.go

from debian:bullseye-slim

workdir /app

copy --from=builder /app/avg-weights-server .

expose 8081

cmd ["./avg-weights-server"]