syntax = 'proto3';

package serverside;

option  go_package = "./serverside";

service AvgWeights {
  rpc AddMyWeights(AddMyWeightsRequest) returns (AddMyWeightsResponse) {}
  rpc GetReleaseWeights(GetReleaseWeightsRequest) returns(GetReleaseWeightsResponse){}
}

message AddMyWeightsRequest{
  // Айдишник пользака
  string client_id = 1;
  // torch.save output (delta с глобальными весами!)
  bytes weights = 2;
  // для weighted FedAvg (сколько примеров было у этого конкретного пользака)
  uint64 num_examples = 3;
}

message AddMyWeightsResponse {}


message GetReleaseWeightsRequest{}

// я пока хз как лучше, прям веса отдавать или просто ссылку на минио.
message GetReleaseWeightsResponse {
  string link_to_minio = 1;
}